---
title: "Feature Selection in LM / subsetting features"
author: "GWU Intro to Data Science DATS 6101"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: yes
  pbaseball_document:
    toc: yes
    toc_depth: '3'
  word_document:
    toc: yes
    toc_depth: '3'
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes a lot of the helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
# Once installed, load the library.
```

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```



```{r, results='markup'}
# Loading our Dataset as 'Data'
data <- read.csv("customer_shopping_data.csv")
head(data)
```

```{r, results='markup'}
#Checking the structure of Data.
str(data)

```
```{r, results='markup'}
summary(data)

```


```{r, results='markup'}
library(skimr)
skim(data)
```



```{r, results='markup'}
#Seeing if there are any missing values in the Data

any(is.na(data))

#Found no missing Data
```
```{r, results='markup'}

any(duplicated(data))


```
```{r, results='markup'}

#data$invoice_date <- as.Date(data$invoice_date, format = "%d/%m/%Y")

head(data)
```


```{r, results='markup'}
library(DataExplorer)
DataExplorer::create_report(data)
```

```{r, results='markup'}
library(ggplot2)

# Create a frequency distribution bar plot using ggplot2
ggplot(data = data, aes(x = gender)) +
  geom_bar() +
  labs(title = "Gender Distribution", x = "Gender", y = "Count")
```


```{r, results='markup'}
library(ggplot2)

# Create a frequency distribution bar plot using ggplot2
ggplot(data = data, aes(x = category)) +
  geom_bar() +
  labs(title = "Category Distribution", x = "Categories", y = "Count")

```

```{r, results='markup'}
library(ggplot2)

# Create a frequency distribution bar plot using ggplot2
ggplot(data = data, aes(x = payment_method)) +
  geom_bar() +
  labs(title = "Payment Method Distribution", x = "Payment Method", y = "Count")
```

```{r, results='markup'}
library(ggplot2)

# Create a frequency distribution bar plot using ggplot2
ggplot(data = data, aes(x = shopping_mall)) +
  geom_bar() +
  labs(title = "Mall Distribution", x = "Shopping Mall", y = "Count")
```
```{r, results='markup'}
# Create a histogram for a continuous variable
hist(data$age, 
     main = "Age Distribution", 
     xlab = "Age", 
     ylab = "Count")

```

```{r, results='markup'}
# Create a histogram for a continuous variable
hist(data$quantity, 
     main = "Quantity Distribution", 
     xlab = "Quantity", 
     ylab = "Count")

```

```{r, results='markup'}
# Create a histogram for a continuous variable
hist(data$price, 
     main = "Price Distribution", 
     xlab = "Price", 
     ylab = "Count")

```
#EDA


```{r, results='markup'}
ggplot(data, aes(x = age)) + geom_bar(fill = "lightblue")

```



```{r, results='markup'}
ggplot(data, aes(x = category)) + geom_bar(fill = "lightgreen")


```

```{r, results='markup'}

ggplot(data, aes(x = age, y = price)) + geom_point(color = "blue")

```

```{r, results='markup'}

ggplot(data, aes(x = gender, y = price, fill = gender)) + geom_boxplot()

```

```{r, results='markup'}
cor(data$age, data$price)


```

```{r, results='markup'}
library(dplyr)

data %>%
  group_by(category) %>%
  summarise(avg_price = mean(price))


```

```{r, results='markup'}


```

```{r, results='markup'}


```

```{r, results='markup'}


```

```{r, results='markup'}


```
